name: todos
on: [push]

jobs:
  todos:
    permissions:
      issues: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        if: github.repository_visibility == 'public'
        uses: "alstr/todo-to-issue-action@v4"
        with:
          AUTO_ASSIGN: true
